version: '2'
services:
    jhipsterauthapp-app:
        image: jhipsterauthapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipsterauthapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterAuthApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipsterauthapp-mongodb:
        extends:
            file: mongodb.yml
            service: jhipsterauthapp-mongodb
